version: "3.7"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_rms_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: profmcdan/rms-api
    command: python manage.py runserver 0.0.0.0:10007
    volumes:
      - ./app:/app
    ports:
      - "10007:10007"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - redis
      - db

  redis:
    image: bitnami/redis:latest
    env_file:
      - ./.env
    ports:
      - "6379:6379"
#    volumes:
#      - ./redis-data:/bitnami/redis/data

  celery:
    <<: *api
    command: celery -A core worker --loglevel=info --logfile=logs/celery.log
    ports: [ ]
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - api

  celery-beat:
    <<: *api
    command: celery -A core beat -l info
    ports: [ ]
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery

  dashboard:
    <<: *api
    command: celery --broker=${REDIS_URL} flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - ./.env
    depends_on:
      - api
      - redis
      - celery

  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./app:/app
    command: -f /app/locustfile.py --master -H http://localhost:8000
    depends_on:
      - api

  locust-worker:
    image: locustio/locust
    volumes:
      - ./app:/app/
    command: -f /app/locustfile.py --worker --master-host locust-master
    depends_on:
      - api

  prometheus:
    image: prom/prometheus:v2.14.0
    volumes:
      - prom_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - api

  grafana:
    image: grafana/grafana:7.1.5-ubuntu
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    restart: unless-stopped
    ports:
      - "3001:3000"
    labels:
      org.label-schema.group: "monitoring"
    depends_on:
      - api

volumes:
  postgres_rms_data: ~
  grafana_data: { }
  prom_data: { }